stages:
- test


sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml



pages:
  image: busybox
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
