stages:
- test
- deploy


sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml


pages:
  image: python:3.8-buster
  stage: deploy
  script:
  - pip install mkdocs>=1.1.2
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
